spring:
  datasource:
    url: jdbc:postgresql://${db.host:localhost}:5432/cloudinn
    username: ${db.user}
    password: ${db.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.user:noreply.fiapark@gmail.com}
    password: ${email.password:lfds sqgo isuo gjnr}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    settings:
      locale: pt_BR
springdoc:
  swagger-ui:
    path: docs.html